### ISSUE TITLE
gulp-Istanbul 1.1.1 is not compatible with gulp-mocha 4.1.0

### ISSUE THREAD

**Issue by dumindux** [SBoudrias/gulp-istanbul#118]
gulp-istanbul fails to show accurate coverage with latest version of gulp-mocha.

**Comment by Enet4** [comment]
I can confirm that there is something problematic happening when using `gulp-mocha` on versions greater than 3.0.1. The latest version now (4.3.0) has issues as well. I have been recently refactoring a project to run all coverage with Gulp rather than `nyc`, and ended up finding this issue, since it showed 90% overall coverage before that.

Here are some coverage summaries. When using any version 4 of `gulp-mocha`:

```
=============================== Coverage summary ===============================
Statements   : 5.28% ( 20/379 ), 12 ignored
Branches     : 3.96% ( 8/202 ), 8 ignored
Functions    : 2.17% ( 2/92 ), 2 ignored
Lines        : 5% ( 18/360 )
================================================================================
```

And when using `gulp-mocha@3.0.1`:

```
=============================== Coverage summary ===============================
Statements   : 91.82% ( 348/379 ), 2 ignored
Branches     : 75.25% ( 152/202 ), 4 ignored
Functions    : 100% ( 92/92 )
Lines        : 91.39% ( 329/360 )
================================================================================
```

Something might have changed in the major version bump that led to this.

**Comment by SBoudrias** [comment]
Please see https://github.com/SBoudrias/gulp-istanbul/issues/115

**Comment by Enet4** [comment]
I understand, but it seems you could use more than a series of closed issues. If this caveat is not documented somewhere (preferably in here, or in `gulp-mocha' otherwise), people will continue making the same mistake.

**Comment by SBoudrias** [comment]
@Enet4 Would you mind sending a PR?
